import '../globals.css'
import DarkModeToggle from './toggle';
import Providers from './Provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-custom-background text-custom-color">
      <body>
        <Providers>
          <DarkModeToggle/>
          {children}
        </Providers>
      </body>
    </html>
  )
}