
import '../globals.css'
import Navbar from '@/components/navbar';
import Providers from './Provider';
import { getPages } from '@/sanity/sanityUtils';

export const metadata = {
  title: 'Arbitrage',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-custom-background text-custom-color max-w-4xl mx-auto py-5 ">
      <body className='mx-5'>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}